### PR TITLE
Cluster: load balancer health check

### PR DESCRIPTION
**Pull request by zammitjames**
## Scope

This allows us to update the health check settings (including the path) of a service via:

```
cluster.addService('service', {
  healthCheck: {
    enabled: true,
    path: '/health',
  },
 ...
})
```

Solves https://github.com/sst/sst/issues/3925

### CODE REVIEW

**Comment by michaelgmcd** [comment]
It looks like the "healthCheck" option is configuring both the target group health check and the container level one. In addition, the type doesn't seem to include "args.healthCheck.command" but uses it. I opened a similar PR for container-level health checks since the target group check can be defined via transform.

**Comment by fwang** [comment]
@zammitjames so there are 2 types of health checks
- container health checks
- load balancer health checks

Looking at the PR, `path`, `retries`, `healthyThreshold`, and `unhealthyThreshold` are load balancer health checks arguments. But they are set on the container.

So to clarify, u r looking to set the load balancer health checks right?

**Comment by zammitjames** [comment]
Yeah exactly - I’d like to modify the health check for the load balancer.

**Comment by fwang** [comment]
Got it. Lemme move it around.

**Comment by fwang** [comment]
Released in 3.2.69. Docs here https://sst.dev/docs/component/aws/cluster#loadbalancer-healthcheck

**Comment by fwang** [comment]
Released v3.2.73 with a minor tweak in how health check is specified - https://sst.dev/docs/component/aws/cluster#loadbalancer-health

/cc @zammitjames @michaelgmcd

**Pull request merged**
